"""lead assignee, drop upload received_chunks

Revision ID: bbbbee1ddde7
Revises: c98665470b74
Create Date: 2026-10-07 21:22:11.251206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (SQLModel column types)
import app.db  # noqa: F401  (UTCDateTime)
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'bbbbee1ddde7'
down_revision: Union[str, Sequence[str], None] = 'c98665470b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignee', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default=''))

    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_column('received_chunks')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('received_chunks', sqlite.JSON(), nullable=False))

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('assignee')

    # ### end Alembic commands ###
