"""initial schema

Revision ID: c98665470b74
Revises: 
Create Date: 2026-10-07 20:39:15.283604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401  (SQLModel column types)
import app.db  # noqa: F401  (UTCDateTime)


# revision identifiers, used by Alembic.
revision: str = 'c98665470b74'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('campaign', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_type', sa.Enum('zip', 'sheet', 'links', 'files', name='sourcetype'), nullable=False),
    sa.Column('agent_type_mode', sa.Enum('ai', 'human', 'column', name='agenttypemode'), nullable=False),
    sa.Column('transcript_script', sa.Enum('roman', 'devanagari', 'english', name='transcriptscript'), nullable=False),
    sa.Column('status', sa.Enum('processing', 'done', 'cancelled', name='batchstatus'), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comparisons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comparisons_scope_hash'), ['scope_hash'], unique=False)

    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_e164', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('follow_up_pending', 'callback_scheduled', 'store_visit_planned', 'won', 'lost', 'not_qualified', name='leadstatus'), nullable=False),
    sa.Column('status_overridden', sa.Boolean(), nullable=False),
    sa.Column('intent_score', sa.Integer(), nullable=True),
    sa.Column('intent_bucket', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('path_summary', sa.JSON(), nullable=True),
    sa.Column('last_call_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_e164')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index('ix_leads_bucket_last_call', ['intent_bucket', 'last_call_at'], unique=False)

    op.create_table('uploads',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mime', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('received_chunks', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('receiving', 'complete', 'failed', name='uploadstatus'), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_type', sa.Enum('ai', 'human', name='agenttype'), nullable=False),
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('campaign', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('upload_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('audio_sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('audio_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('call_datetime', app.db.UTCDateTime(), nullable=True),
    sa.Column('stage', sa.Enum('queued', 'downloading', 'preparing', 'transcribing', 'analysing', 'done', name='callstage'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', 'skipped', name='callstatus'), nullable=False),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calls_audio_sha256'), ['audio_sha256'], unique=False)
        batch_op.create_index('ix_calls_batch_status', ['batch_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_lead_id'), ['lead_id'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_lead_id'), ['lead_id'], unique=False)

    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('say', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('why', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('ai', 'manual', name='actionsource'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actions_lead_id'), ['lead_id'], unique=False)

    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('quality_pct', sa.Float(), nullable=True),
    sa.Column('intent_score', sa.Integer(), nullable=True),
    sa.Column('intent_bucket', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('disposition', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyses_call_id'), ['call_id'], unique=False)

    op.create_table('job_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.Enum('queued', 'downloading', 'preparing', 'transcribing', 'analysing', 'done', name='callstage'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', 'skipped', name='callstatus'), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.create_index('ix_job_events_batch', ['batch_id', 'id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('queued', 'downloading', 'preparing', 'transcribing', 'analysing', 'done', name='callstage'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', name='jobstatus'), nullable=False),
    sa.Column('run_after', app.db.UTCDateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('locked_at', app.db.UTCDateTime(), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_call_id'), ['call_id'], unique=False)
        batch_op.create_index('ix_jobs_claim', ['status', 'stage', 'run_after'], unique=False)

    op.create_table('metrics',
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('call_id')
    )
    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('script', sa.Enum('roman', 'devanagari', 'english', name='transcriptscript'), nullable=False),
    sa.Column('segments', sa.JSON(), nullable=False),
    sa.Column('speaker_map', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcripts_call_id'), ['call_id'], unique=False)

    op.create_table('transcript_cache',
    sa.Column('audio_sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transcript_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], ),
    sa.PrimaryKeyConstraint('audio_sha256')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcript_cache')
    with op.batch_alter_table('transcripts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcripts_call_id'))

    op.drop_table('transcripts')
    op.drop_table('metrics')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_claim')
        batch_op.drop_index(batch_op.f('ix_jobs_call_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.drop_index('ix_job_events_batch')

    op.drop_table('job_events')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_call_id'))

    op.drop_table('analyses')
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actions_lead_id'))

    op.drop_table('actions')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_lead_id'))

    op.drop_table('notes')
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calls_lead_id'))
        batch_op.drop_index('ix_calls_batch_status')
        batch_op.drop_index(batch_op.f('ix_calls_audio_sha256'))

    op.drop_table('calls')
    op.drop_table('uploads')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index('ix_leads_bucket_last_call')

    op.drop_table('leads')
    with op.batch_alter_table('comparisons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comparisons_scope_hash'))

    op.drop_table('comparisons')
    op.drop_table('batches')
    # ### end Alembic commands ###
